application: wcs-hub
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /
  login: required
  static_files: index.html
  upload: index.html
- url: /static/
  login: required
  static_dir: static
- url: /partials/
  login: required
  static_dir: partials

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
